### ISSUE TITLE
Null pointer when adding a new experiment

### ISSUE THREAD

**Issue by jezekp** [INCF/eeg-database#125]
When I click to a finish button on new experiment wizard I get a null pointer exception:

java.lang.NullPointerException
     at cz.zcu.kiv.eegdatabase.data.nosql.ElasticSynchronizationInterceptor.syncExperimentParams(ElasticSynchronizationInterceptor.java:215)
     at cz.zcu.kiv.eegdatabase.data.nosql.ElasticSynchronizationInterceptor.onSave(ElasticSynchronizationInterceptor.java:92)

Test environment

**Comment by rinkesj** [comment]
fixed, test it and close issue.

**Comment by pbruha** [comment]
Adding experiment still not working - I get a null pointer exception:
Last cause: not-null property references a null or transient value: cz.zcu.kiv.eegdatabase.data.pojo.Experiment.weather
WicketMessage: Method onFormSubmitted of interface org.apache.wicket.markup.html.form.IFormSubmitListener targeted at [Form [Component id = form]] on component [Form [Component id = form]] threw an exception

**Comment by rinkesj** [comment]
I had forgotten in the database will be constraint. My fault.

**Comment by rinkesj** [comment]
Ok i will send you another 4 SQL commands. We need remove that constraints and its fixed. I created new experiment and try edit.
